name: Update Daily DSA

on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:

jobs:
  update-dsa:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run update script
        run: python scripts/update_dsa.py

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Updated today's DSA problem"
          git push

